# Business Requirement Document (BRD)

## 1. Giới thiệu
- Mục tiêu dự án: ...
- Phạm vi: ...

## 2. Yêu cầu nghiệp vụ
### 2.1 Quản lý Khách hàng
- Mô tả: ...
- Luồng xử lý: ...

### 2.2 Quản lý Hợp đồng
- Mô tả: ...
- Luồng xử lý: ...

## 3. Ràng buộc
- Các yếu tố pháp lý, kỹ thuật, vận hành...

## 4. Phụ lục
- Tài liệu tham khảo
- Biểu mẫu liên quan
